version: "1"
services:
  django:
    build: 
      context: .
      dockerfile: django.docker
    working_dir: /app

    ports:
      - "8000:8000"
    
    container_name: tpumpRandomizer-django

  nginx:
    build: 
      context: .
      dockerfile: nginx.docker
    image: nginx:latest

    ports:
      - "80:80"
      - "433:433"


    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf

    - ./tpumpRandomizer/static/html:/static/html # Mount Django static files for Nginx to serve
    - ./tpumpRandomizer/static/css:/static/css    # Use Shell Script to move them all to root static
    - ./tpumpRandomizer/static/js:/static/js
    - ./tpumpRandomizer/static/favicon:/static/favicon

    container_name: tpumpRandomizer-nginx
