version: "1"
services:
  web:
    build: 
      context: .
    working_dir: /app

    command: ["python", "manage.py", "runserver", "0.0.0.0:8001"]

    ports:
      - "8001:8001"
    
    container_name: tpumpRandomizer